version: "3"
services:
  geth:
    restart: "no"
    user: ${LOCAL_UID}:${LOCAL_UID}
    build:
      context: ./geth
      args:
        - BUILD_TARGET=${GETH_BUILD_TARGET} 
        - USER=${GETH_USER}
        - UID=${LOCAL_UID}
    image: geth
    volumes:
      - geth-data:/var/lib/goethereum
    ports:
      - ${GETH_PORT}:30303/tcp
      - ${GETH_PORT}:30303/udp
    expose:
      - 8545
    entrypoint: ${GETH_ENTRYPOINT}
    command:
      - ${ETH_NETWORK}
  beacon:
    depends_on:
      - geth
  eth2:
    depends_on:
      - geth
volumes:
  geth-data:
