version: "3"
services:
  beacon:
    restart: "no"
    user: ${LOCAL_UID}:${LOCAL_UID}
    build:
      context: ./lighthouse
      args:
        - BUILD_TARGET=${LH_BUILD_TARGET}
        - USER=${LH_USER}
        - UID=${LOCAL_UID}
    image: lighthouse
    volumes:
      - lhbeacon-data:/var/lib/lighthouse
    ports:
      - ${LH_PORT}:9000/tcp
      - ${LH_PORT}:9000/udp
    expose:
      - 5052
    entrypoint: wait-for-eth1.sh ${ETH1_NODE} ${LH_BN_ENTRYPOINT}
    command:
      - --testnet
      - ${TESTNET}
      - --eth1-endpoint
      - ${ETH1_NODE}
  validator:
    restart: "no"
    user: ${LOCAL_UID}:${LOCAL_UID}
    build:
      context: ./lighthouse
      args:
        - BUILD_TARGET=${LH_BUILD_TARGET}
        - USER=${LH_USER}
        - UID=${LOCAL_UID}
    image: lighthouse
    volumes:
      - lhvalidator-data:/var/lib/lighthouse
    entrypoint: ${LH_VAL_ENTRYPOINT}
    command: ["validator", "--server", "http://beacon:5052", "--graffiti", "${GRAFFITI}", "--testnet", "${TESTNET}"]
    depends_on:
      - beacon
  validator-import:
    restart: "no"
    user: ${LOCAL_UID}:${LOCAL_UID}
    image: lighthouse
    build:
      context: ./lighthouse
      args:
        - BUILD_TARGET=${LH_BUILD_TARGET}
        - USER=${LH_USER}
        - UID=${LOCAL_UID}
    volumes:
      - lhvalidator-data:/var/lib/lighthouse
      - ${DEPCLI_LOCALDIR}/validator_keys:/var/lib/lighthouse/validator_keys
    entrypoint: ${LH_VAL_ENTRYPOINT}
    command: ["account", "validator", "import", "--directory", "/var/lib/lighthouse/validator_keys", "--validator-dir", "/var/lib/lighthouse"]
  deposit-cli:
    restart: "no"
    user: ${LOCAL_UID}:${LOCAL_UID}
    build:
      context: ./eth2.0-deposit-cli
      args:
        - BUILD_TARGET=${DEPCLI_BUILD_TARGET}
        - USER=${DEPCLI_USER}
        - UID=${LOCAL_UID}
    image: eth2.0-deposit-cli
    volumes:
      - ${DEPCLI_LOCALDIR}:/var/lib/depcli-data
    entrypoint: ${DEPCLI_ENTRYPOINT}
    command:
      - --num_validators
      - ${NUMVAL}
      - --chain
      - ${DEPOSIT_CHAIN}
  eth2:
    image: tianon/true
    restart: "no"
    depends_on:
      - beacon
      - validator
volumes:
  lhbeacon-data:
  lhvalidator-data:
