version: "3"
services:
  beacon:
    restart: "no"
    user: ${LOCAL_UID}:${LOCAL_UID}
    build:
      context: ./prysm
      args:
        - BUILD_TARGET=${PRYSM_BUILD_TARGET}
        - USER=${PRYSM_USER}
        - UID=${LOCAL_UID}
    image: prysm
    volumes:
      - prysmbeacon-data:/var/lib/prysm
    ports:
      - ${PRYSM_PORT}:13000/tcp
      - ${PRYSM_UDP_PORT}:12000/udp
    expose:
      - 4000
      - 8080
    entrypoint: ${PRYSM_BN_ENTRYPOINT}
    command:
      - beacon-chain
      - --datadir
      - /var/lib/prysm/
      - --rpc-host
      - 0.0.0.0
      - --monitoring-host
      - 0.0.0.0
      - --p2p-host-ip
      - $$ClientIP
      - --http-web3provider
      - ${ETH1_NODE}
      - --spadina
  validator:
    restart: "no"
    user: ${LOCAL_UID}:${LOCAL_UID}
    build:
      context: ./prysm
      args:
        - BUILD_TARGET=${PRYSM_BUILD_TARGET}
        - USER=${PRYSM_USER}
        - UID=${LOCAL_UID}
    image: prysm
    volumes:
      - prysmvalidator-data:/var/lib/prysm
    expose:
      - 8081
    entrypoint: wait-for-beacon.sh beacon:4000 ${PRYSM_VAL_ENTRYPOINT}
    command: 
      - --monitoring-host
      - 0.0.0.0
      - --beacon-rpc-provider
      - beacon:4000
      - --graffiti
      - ${GRAFFITI}
      - --spadina
      # If you chose not to store the wallet password during import, comment out the two following lines
      - --wallet-password-file
      - /var/lib/prysm/password.txt
    depends_on:
      - beacon
  validator-import:
    restart: "no"
    user: ${LOCAL_UID}:${LOCAL_UID}
    image: prysm
    build:
      context: ./prysm
      args:
        - BUILD_TARGET=${PRYSM_BUILD_TARGET}
        - USER=${PRYSM_USER}
        - UID=${LOCAL_UID}
    volumes:
      - prysmvalidator-data:/var/lib/prysm
      - ${DEPCLI_LOCALDIR}/validator_keys:/var/lib/prysm/validator_keys
    entrypoint: ${PRYSM_VAL_IMPORT_ENTRYPOINT}
    command:
      - validator
      - --datadir
      - /var/lib/prysm
      - --wallet-dir
      - /var/lib/prysm/
      - accounts-v2
      - import
      - --keys-dir
      - /var/lib/prysm/validator_keys
      - --spadina
  deposit-cli:
    restart: "no"
    user: ${LOCAL_UID}:${LOCAL_UID}
    build:
      context: ./eth2.0-deposit-cli
      args:
        - BUILD_TARGET=${DEPCLI_BUILD_TARGET}
        - USER=${DEPCLI_USER}
        - UID=${LOCAL_UID}
    image: eth2.0-deposit-cli
    volumes:
      - ${DEPCLI_LOCALDIR}:/var/lib/depcli-data
    entrypoint: ${DEPCLI_ENTRYPOINT}
    command:
      - --num_validators
      - ${NUMVAL}
      - --chain
      - ${DEPOSIT_CHAIN}
  eth2:
    image: tianon/true
    restart: "no"
    depends_on:
      - beacon
      - validator
volumes:
  prysmbeacon-data:
  prysmvalidator-data:
