version: "3"
services:
  geth:
    restart: "no"
    user: ${LOCAL_UID}:${LOCAL_UID}      
    build:
      context: ./geth
      args:
        - BUILD_TARGET=${GETH_BUILD_TARGET} 
        - USER=${GETH_USER}
        - UID=${LOCAL_UID}
    image: geth
    volumes:
      - geth-data:/var/lib/goethereum
    ports:
      - ${GETH_PORT}:30303/tcp
      - ${GETH_PORT}:30303/udp
    expose:
      - 8545
    entrypoint: ${GETH_ENTRYPOINT}
    command:
      - ${ETH_NETWORK}
  lh-beacon:
    restart: "no"
    user: ${LOCAL_UID}:${LOCAL_UID}
    build:
      context: ./lighthouse
      args:
        - BUILD_TARGET=${LH_BUILD_TARGET}
        - USER=${LH_USER}
        - UID=${LOCAL_UID}
    image: lighthouse
    volumes:
      - lhbeacon-data:/var/lib/lighthouse
    ports:
      - ${LH_PORT}:9000/tcp
      - ${LH_PORT}:9000/udp
    expose:
      - 5052
    entrypoint: bash -c "wait-for-eth1.sh ${LH_ETH1_NODE} ${LH_BN_ENTRYPOINT}"
    command:
      - --testnet
      - ${LH_TESTNET}
      - --eth1-endpoint
      - ${LH_ETH1_NODE}
  lh-validator:
    restart: "no"
    user: ${LOCAL_UID}:${LOCAL_UID}
    build:
      context: ./lighthouse
      args:
        - BUILD_TARGET=${LH_BUILD_TARGET}
        - USER=${LH_USER}
        - UID=${LOCAL_UID}
    image: lighthouse
    volumes:
      - lhvalidator-data:/var/lib/lighthouse
    entrypoint: ${LH_VAL_ENTRYPOINT}
    command: ["validator", "--server", "http://lh-beacon:5052", "--graffiti", ${GRAFFITI}]
  lh-validator-import:
    restart: "no"
    user: ${LOCAL_UID}:${LOCAL_UID}
    image: lighthouse
    build:
      context: ./lighthouse
      args:
        - BUILD_TARGET=${LH_BUILD_TARGET}
        - USER=${LH_USER}
        - UID=${LOCAL_UID}
    volumes:
      - lhvalidator-data:/var/lib/lighthouse
      - ${DEPCLI_LOCALDIR}/validator_keys:/var/lib/lighthouse/validator_keys
    entrypoint: ${LH_VAL_ENTRYPOINT}
    command: ["account", "validator", "import", "--directory", "/var/lib/lighthouse/validator_keys", "--validator-dir", "/var/lib/lighthouse"]
  deposit-cli:
    restart: "no"
    user: ${LOCAL_UID}:${LOCAL_UID}
    build:
      context: ./eth2.0-deposit-cli
      args:
        - BUILD_TARGET=${DEPCLI_BUILD_TARGET}
        - USER=${DEPCLI_USER}
        - UID=${LOCAL_UID}
    image: eth2.0-deposit-cli
    volumes:
      - ${DEPCLI_LOCALDIR}:/var/lib/depcli-data
    entrypoint: ${DEPCLI_ENTRYPOINT}
    command:
      - --num_validators
      - ${NUMVAL}
      - --chain
      - ${DEPOSIT_CHAIN}
  eth2:
    image: tianon/true
    restart: "no"
    depends_on:
      - geth
      - lh-beacon
      - lh-validator
  eth2-3rd:
    image: tianon/true
    restart: "no"
    depends_on:
      - lh-beacon
      - lh-validator
volumes:
  geth-data:
  lhbeacon-data:
  lhvalidator-data:
