global:
  scrape_interval:     15s 
  evaluation_interval: 15s 
scrape_configs:
  - job_name: 'nimbus'
    static_configs:      
      - targets: ['beacon:8008']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']
