# Runs a full archive geth node with http and ws endpoints, available on the host network
# Included for Nimbus, which requires a full archive geth. In main net, this would require
# ~2TB storage. For Goerli, it is ~80GB
version: "3"
services:
  geth:
    restart: "no"
    user: ${LOCAL_UID}:${LOCAL_UID}
    build:
      context: ./geth
      args:
        - BUILD_TARGET=${GETH_BUILD_TARGET} 
        - USER=${GETH_USER}
        - UID=${LOCAL_UID}
    image: geth
    volumes:
      - geth-data:/var/lib/goethereum
    ports:
      - ${GETH_PORT}:30303/tcp
      - ${GETH_PORT}:30303/udp
      - ${GETH_HTTP_PORT}:8545/tcp
      - ${GETH_WS_PORT}:8546/tcp
    entrypoint: ${GETH_ENTRYPOINT}
    command:
      - ${ETH_NETWORK}
      - --gcmode archive
      - --ws
      - --ws.api
      - eth,net
      - --ws.addr
      - 0.0.0.0
  beacon:
    depends_on:
      - geth
  eth2:
    depends_on:
      - geth
volumes:
  geth-data:
